### ISSUE TITLE
TODO 2020

### ISSUE THREAD

**Issue by cafcustodio** [Kazuo256/guiadobixo#108]
- [x] Capa
- [ ] Verificar todos os %REFTIME (referências a uma data que pode mudar)
- [ ] Arrumar o máximo de %FIXME possíveis
- [x] Conferir os links dos sites no guia (atualizá-los caso necessário)
- [x]  Revisar seção “Editorial”
- [ ] Atualizar o QR code
- [x] Revisar seção “Carta aos Ingressantes”
- [x]  Revisar seção “Dez mandamentos”
- [x]  Revisar seção “7 pecados”
- [x] Revisar seção “Comissão de Trote e Kit-bixo”
- [x] Atualizar data do AnIME-se
- [x] Atualizar descrição do kit bixo
- [ ] Repassar os textos para as entidades atualizarem:
     + [x] CAMat
     + [x] Atlética
     + [x] Atualizar data do BichUSP
     + [x] Prêmios do BichUSP 2019
     + [x] Campeão do BIFE 2019
     + [x] Títulos
     + [x] Contato AAAMat
     + [x] RDs
     + [x] Rede Linux
        + [ ] Conferir e atualizar a informação de que o Bloco A fecha à 0h (está numa footnote)
     + [x] IME Jr.
     + [x] MaratonIME
     + [x] USPCodeLab
     + [x] USPGameDev
     + [x] IMEsec
     + [x] Hardware Livre
     + [x] Tecs
     + [x] DiversIME
     + [x] Existimos
     + [x] CAM
     + [x] CinIME
     + [x] Grupo A5
     + [x] Olimpíadas de Conhecimento
     + [x] CCSL
     + [x] CRInt
     + [x]  CEC
     + [x]  CAEM
     + [x]  Biblioteca
     + [ ] Adicionar qualquer entidade que possa ter surgido
- [x] Adicionar texto sobre cursos do CEPEUSP
- [x] Atualizar textos dos cursos:
     + [x] BCC
     + [x] Estat
     + [x] Pura
     + [x] Licenciatura
     + [x] Aplicada
     + [x] BMAC
- [x]  Revisar seção “Um pouco sobre o IME”
    + [x] Conferir telefones: seção de alunos - 30916149 30916279
    + [x] Procurar e adicionar o horário de funcionamento do Xerox
- [x]  Atualizar datas de matrícula
- [x]  Confirmar horários da seção de alunos
- [x]  Revisar seção “JupiterWeb”
- [x] Revisar seção “Um pouco sobre a USP”
    + [x] Conferir o horário de funcionamento da AMORCRUSP
    + [x] Atualizar informação dos bandejões:
        + [x] A tabela está dizendo que a Física serve café da manhã. corrigir
        + [x] Conferir horários
        + [x] PCO vai abrir ou não?
- [x]  Revisar SAS
- [x] Revisar informações sobre wi-fi
- [x] Revisar seção “Tudo que vai volta”
    + [x] MAPA DO 8032!!!
    + [x] Intermunicipais: verificar e atualizar sites, telefones e informações
    + [x] Táxi: verificar e atualizar horários e telefones
    + [ ] *adicionar se der: breve texto sobre transporte por aplicativo dentro do campus, basicamente pro bixo saber que muito Uber cancela viagem com partida de dentro da USP à noite porque a entrada é controlada.
- [x] Revisar jogos de vivência
- [x] Revisar seção “Dicas”
- [x] Cultura na USP
- [x]  Onde beber?
- [x]  Revisar seção “Músicas para a bixarada”
- [x]  Revisar seção “Utilidades” (excluir a página de Segredos)
    + [x] Verificar telefones: 30913581 setor de passe escolar; 30914313 telefonista da usp; 0800 012 090 disk trote; 30371773 orelhão do IME ("plantão de cálculo e algelin")
- [x]  Revisar seção “Glossário” 
- [x]  Revisar seção “Considerações finais”

**Comment by cafcustodio** [comment]
Já entrei em contato com DiversIME, revisei textos do CAM, CAEM, Lic (seria legal mais uma pessoa ler) e Grupo A5. Também já comecei o textinho sobre o CEPE. 

Coloquem ✔ nos textos que revisarem, usem a listinha e se lembrarem de mais alguma coisa, adicionem!

Qualquer dúvida, fale comigo. Beijuuuu

**Comment by rafa4** [comment]
Editei o texto do transporte pra colocar o 8032, falta encontrar/fazer o mapa da rota dele e colocar lá. Atualizei também os horários dos portões e uma informação provavelmente antiga (nos finais de semana não entra só circular na usp, entra também o 702U)

**Comment by Pedro9Paulo** [comment]
editei o texto do bcc, 2019 pra 2020, enviei pros grupos de extensão arrumarem seus textos, exclui a página de segredos,

**Comment by rafa4** [comment]
como eu edito a listinha, gente? não consigo

**Comment by suhalonso** [comment]
> como eu edito a listinha, gente? não consigo

Oi Rafa! Eu acho que tem que ser collaborator pra editar a listinha diretamente. No caso, precisaria pedir para o Wil te adicionar como collaborator ou pedir para alguém que seja marcar na listinha por você. Eu e a Camila podemos fazer isso.

**Comment by rafa4** [comment]
Tranquilo! Vou escrevendo por aqui conforme edito então, daí vcs podem marcar, por favor? Obrigadooo

**Comment by rafa4** [comment]
Para marcar na checklist:
Carta aos ingressantes revisada
Descrição do kit bixo atualizada
Sete pecados revisados (pecado sobre a máquina de café atualizado)

Mais alterações:
Sobre o IME - Seção de alunos: substituí a parte sobre a matrícula presencial, porque não é mais lá, por uma piadinha (ruim) sobre trancamento de matrícula. Mas mantive o %REFTIME que tem pra verificarmos nos outros anos caso volte a ser lá

**Comment by estevaodias370** [comment]
Também tô sem acesso à edição da listinha. Revisei e dei uma pequena ampliada no texto da Estat.

**Comment by Pedro9Paulo** [comment]
imesec revisou e vai deixar o texto igual

**Comment by rafa4** [comment]
links estão conferidos e corrigidos (exceto os que estão dentro de textos de entidades, preferi esperar até elas atualizarem)

**Comment by rafa4** [comment]
sobre datas de matrícula: elas estavam na parte da seção de alunos, porque a matrícula era feita lá. agora que não é mais, tirei de lá (vide correções de anteontem abaixo). não tinha me preocupado em colocar em outro lugar porque considerei que o bixo vai receber o guia na própria matrícula (o que, agora que eu parei pra pensar, deve estar errado), mas também não sei onde dá para colocar. por favor, renomear o tópico "Atualizar datas de matrícula" para "Reinserir datas de matrícula"!

> Sobre o IME - Seção de alunos: substituí a parte sobre a matrícula presencial, porque não é mais lá, por uma piadinha (ruim) sobre trancamento de matrícula. Mas mantive o %REFTIME que tem pra verificarmos nos outros anos caso volte a ser lá

**Comment by rafa4** [comment]
depois de ler o guia quase inteiro umas três vezes eu identifiquei que precisamos fazer tudo isso que está aqui embaixo. Alguém pode editar o to do pra incluir/detalhar mais essas coisas, por favor?

Na parte do Júpiter: (só precisa fazer essas coisas, todo o resto está revisado e certinho)
-colocar Bilhete Único SPTrans em "Acompanhamentos"
-colocar link do vídeo da matrícula em "Matrícula"
-explicar o que é a seção "Cartão USP"

Um pouco sobre o IME: (só precisa fazer essas coisas, todo o resto está revisado e certinho)
-conferir telefones: seção de alunos - 30916149 30916279
-procurar e adicionar o horário de funcionamento do CAEM
-procurar e adicionar o horário de funcionamento do Xerox

Rede Linux: (texto de entidade)
-conferir e atualizar a informação de que o Bloco A fecha à 0h (está numa footnote)

Um pouco sobre a USP: (todo o resto está revisado e certinho, exceto parte do SAS, que não sei se todas as informações estão atualizadas)
-conferir o horário de funcionamento da AMORCRUSP
-atualizar informação dos bandejões:
--a tabela está dizendo que a Física serve café da manhã. corrigir
--conferir horários
--PCO vai abrir ou não?

Tudo que vai volta: (só precisa fazer essas coisas, todo o resto está revisado e certinho)
-MAPA DO 8032!!!
-Intermunicipais: verificar e atualizar sites, telefones e informações
-Táxi: verificar e atualizar horários e telefones
*adicionar se der: breve texto sobre transporte por aplicativo dentro do campus, basicamente pro bixo saber que muito Uber cancela viagem com partida de dentro da USP à noite porque a entrada é controlada.

Utilidades: (só precisa fazer isso, todo o resto está revisado e certinho)
-verificar telefones: 30913581 setor de passe escolar; 30914313 telefonista da usp; 0800 012 090 disk trote; 30371773 orelhão do IME ("plantão de cálculo e algelin")

**Comment by rafa4** [comment]
E também tem umas seções revisadas e com tudo ok:

Informações sobre wifi revisadas
Onde beber revisado
Glossário revisado
Considerações finais revisadas

**Comment by Pedro9Paulo** [comment]
pelo que eu vi existe um aplicativo agora do disk-trote então talvez o número esteja realmente obsoleto, mas mesmo que não acho bom incluir um aplicativo

**Comment by cafcustodio** [comment]
Existimos
CCSL
CRInt 
CEC
IMEJr

**Comment by cafcustodio** [comment]
Dez Mandamentos 
Hardware Livre 
Tecs
Olimpíadas de Conhecimento

**Comment by cafcustodio** [comment]
Biblioteca

**Comment by cafcustodio** [comment]
Biblioteca
Aplicada
SAS

**Comment by estevaodias370** [comment]
Tudo ok na seção Cultura na Usp

**Comment by cafcustodio** [comment]
Pura ok

**Comment by cafcustodio** [comment]
Dicas ok

**Comment by cafcustodio** [comment]
USPCodeLab
Jogos de Vivência

**Comment by cafcustodio** [comment]
CAM atualizado com os dados da nova gestão

**Comment by rafa4** [comment]
atlética - tudo feito
