### ISSUE TITLE
TODO 2019

### ISSUE THREAD

**Issue by gfth4x07** [Kazuo256/guiadobixo#46]
+ [x] Capa (Ju Lobato fez umas artes incríveis)
+ [ ] Verificar todos os %REFTIME (referências a uma data que pode mudar)
+ [ ] Arrumar o máximo de %FIXME possíveis
+ [x] Conferir os links dos sites no guia (atualizá-los caso necessário)
+ [x] Atualizar todos os “Comissão de Trote” por “Comissão de Recepção”
+ [x] Colocar linguagem neutra no guia (bixo -> bixe, veterano -> veterane)
+ [x] Fazer textinho explicando o porquê de usar a linguagem neutra
+ [x] Revisar seção “Editorial”
	+ [x] Atualizar o QR code
+ [x] Revisar seção “Carta aos Ingressantes”
+ [x] Revisar seção “Dez mandamentos”
+ [x] Revisar seção “7 pecados”
+ [x] Revisar seção “Comissão de Trote e Kit-bixo”
	+ [x] Atualizar data do AnIME-se
	+ [x] Atualizar descrição do kit bixo
+ [ ] Repassar os textos para as entidades atualizarem:
	+ [ ] CAMat
	+ [x] Atlética
		+ [x] Atualizar data do BichUSP
		+ [x] Prêmios do BichUSP 2018
		+ [x] Campeão do BIFE 2018
		+ [x] Títulos
		+ [x] Contato AAAMat
	+ [ ] RDs
	+ [ ] Rede Linux
	+ [x] IME Jr.
	+ [x] MaratonIME
	+ [x] USPCodeLab
	+ [x] USPGameDev
	+ [x] IMEsec
	+ [x] Hardware Livre
	+ [x] Tecs
	+ [x] DiversIME
	+ [x] Existimos
	+ [x] Adicionar a CAM
	+ [ ] CinIME
		+ [x] Acrescentar logo
	+ [x] Grupo A5
	+ [ ] Olimpíadas de Conhecimento
	+ [x] CCSL
	+ [x] CRInt
	+ [x] CEC
	+ [x] CAEM
	+ [x] Biblioteca
	+ [x] Adicionar qualquer entidade que possa ter surgido
+ [x] Atualizar textos dos cursos
	+ [x] BCC
	+ [x] Estat
	+ [ ] Pura
	+ [x] Licenciatura
		+ [x] Atualizar todos os AACC no guia por ATPA
	+ [x] Aplicada
	+ [x] BMAC
+ [x] Revisar seção “Um pouco sobre o IME”
	+ [ ] Colocar mapinhas do Edu
	+ [x] Atualizar datas de matrícula
	+ [x] Confirmar horários da seção de alunos
+ [x] Revisar seção “JupiterWeb”
+ [x] Revisar seção “Um pouco sobre a USP”
	+ [ ] SAS
	+ [x] Atualizar preços dos restaurantes
	+ [x] Acrescentar informações sobre wi-fi
	+ [x] Verificar sobre o e-mail USP: bixes recebem o e-mail na matrícula?
+ [x] Revisar seção “Tudo que vai volta”
	+ [x] Ônibus!! Precisa ver quais linhas vão passar no ano que vem e listar no guia. E tem os fretados tb.
+ [x] Guia de jogos de vivência:
Ideia do PP: fazer um forms para saber os jogos mais jogados, atualizando de acordo com as respostas
+ [x] Revisar seção “Dicas”
	+ [x] Cultura na USP
	+ [ ] Onde beber?
+ [x] Revisar seção “Músicas para a bixarada”
+ [x] Revisar seção “Utilidades” (podemos acrescentar a página de Segredos)
+ [x] Revisar seção “Glossário” (manter PUTUSP? retirar pf)
+ [x] Revisar seção “Considerações finais”

**Comment by suhalonso** [comment]
Teste de comentário

**Comment by suhalonso** [comment]
[Acrescentar informações sobre wi-fi] Vou tentar escrever um textinho sobre esse aqui :)

**Comment by suhalonso** [comment]
[Licenciatura] Vou revisar o texto da lic e mudar as ocorrências de AACC por ATPA

**Comment by suhalonso** [comment]
[Carta aos ingressantes] Vou revisar essa seção

**Comment by suhalonso** [comment]
[Comissão de trote e kit bixo] Vou revisar essa seção, ainda vai faltar atualizar a data do anime-se e o link do facebook (mas eles já estão contemplados em outros itens a serem feitos)

**Comment by suhalonso** [comment]
[JupiterWeb] Vou revisar!

**Comment by suhalonso** [comment]
[Um pouco sobre o IME] Vou dar uma olhadinha

**Comment by cafcustodio** [comment]
Revisando textos abaixo: 

Lic
Biblioteca
Grupo A5
IME Jr.
CEC
CAEM

obs.: O Existimos está em pausa! Vamos deixar apenas a CAM ou citar os dois no guia?

**Comment by cafcustodio** [comment]
Página do fb Segredos IME-USP acrescentada no Utilidades

**Comment by cafcustodio** [comment]
Revisando DiversIME, Existimos, Rede Linux, CCSL e CRInt

**Comment by cafcustodio** [comment]
Revisando DiversIME, Existimos, CCSL e CRInt

**Comment by suhalonso** [comment]
[Dicas] Vou olhar a parte de cultura na USP

**Comment by suhalonso** [comment]
Revisei Glossário, Considerações finais, 7 pecados e 10 mandamentos

**Comment by suhalonso** [comment]
O Paulo Marçal disse que vai conferir os links dos sites do guia e substituir "Comissão de Trote" por "Comissão de Recepção"

**Comment by Pedro9Paulo** [comment]
vou revisar o texto do BCC, colocar o link do yggdrasil

**Comment by cafcustodio** [comment]
Revisando texto da Estat e textinho pra CAM

**Comment by suhalonso** [comment]
[Tudo que vai volta] Vou revisar essa seção!

**Comment by suhalonso** [comment]
> [Tudo que vai volta] Vou revisar essa seção!

Gente, parece até que faz alguns séculos que essa seção foi atualizada kkk

**Comment by suhalonso** [comment]
[Cursos de verão] Criei um arquivo descrevendo brevemente os cursos de verão do IME, o que vocês acham?

**Comment by suhalonso** [comment]
Fiz um parágrafo bem curtinho sobre linguagem neutra...
Nós vamos mesmo só trocar bixo -> bixe e veterano -> veterane ou vamos fazer mais alguma coisa?
No parágrafo, coloquei como se fossemos fazer somente as substituições acima.
Ele está no editorial (não sei se é adequado colocar aí ou se tem um lugar melhor).
Talvez alguém mais engajado no assunto saiba escrever um parágrafo melhor que o meu.

**Comment by suhalonso** [comment]
[Um pouco sobre a USP] Vou revisar, excluindo-se os itens nele identados (tudo sobre o SAS, e-mail USP e lugares pra comer que não são o bandejão)

**Comment by suhalonso** [comment]
Coloquei o logo do CinIME

**Comment by Pedro9Paulo** [comment]
A pesquisa mostrou Fodinha como jogo mais jogado do IME, vou escrever o texto com as regras, aproveitei e coloquei a mão de ferro no truco
